안녕하세요. 인천대학교 로보틱스 & 에너지융합 연구실 석사과정 박동식 입니다.



이전에 제가 작성했던 코드 일부분 공유드립니다.

이외 데이터 시트, 도면, 사용자 매뉴얼은 아래 링크 참조하시면 되십니다.



https://rainbowrobotics.github.io/rb_cobot_docs/ko/



감사합니다.

박동식 드림







_______________________________________________

박동식 / 석사과정
인천대학교 바이오-로봇시스템공학과
로보틱스&에너지융합 연구실 
_______________________________________________
Dong Sik Park /  M.S. student
Robotics & Energy Convergence Lab (Prof. Woo Yong Kim)
Department of Biomedical & Robotics Engineering,
College of Engineering, Incheon National University
E-mail: dsp_robotics@inu.ac.kr
Mobile: +82-10-8709-7960





['BlendingOption', 'Cobot', 'CobotData', 'CollisionFollowUpMode', 'CollisionMode', 'ControlBoxInfo', 'DigitalIOMode', 'Endian', 'ErrorCodeMessage', 'GripperConnectionPoint', 'GripperModel', 'ICE_INFO_AMBI_HIGH', 'ICE_INFO_AMBI_LOW', 'ICE_INFO_CONNECTED', 'ICE_INFO_MODE_COMM', 'ICE_INFO_MODE_CUP', 'ICE_INFO_REQUESTING', 'ICE_INFO_TIME_ICE', 'ICE_INFO_TIME_WATER', 'ICE_INFO_TMEP_AMBI', 'ICE_INFO_TMEP_CONDEN', 'ICE_INFO_TMEP_EVAPO', 'ICE_INFO_USING', 'ICE_INFO_VECSIZE', 'ICE_STATE_COMM_MODE', 'ICE_STATE_COMP_WORK', 'ICE_STATE_CUP_LEVEL', 'ICE_STATE_ERR_1', 'ICE_STATE_ERR_2', 'ICE_STATE_ERR_3', 'ICE_STATE_ERR_4', 'ICE_STATE_ERR_CODE', 'ICE_STATE_FULL_ICE', 'ICE_STATE_LAST_ICE_NO', 'ICE_STATE_LAST_ICE_YES', 'ICE_STATE_MOTOR_WORK', 'ICE_STATE_OUT_SOL', 'ICE_STATE_RD', 'JRT_ENCODER', 'JRT_JEGB', 'JRT_JEGG', 'Message', 'MoveCOrientationOption', 'MoveCRotationOption', 'MoveITPLOption', 'MoveLBOption', 'MoveLCOption', 'MoveLCProperty', 'MovePBOption', 'MoveServoTOption', 'OR_2FG7_MAX_EXT', 'OR_2FG7_MAX_INT', 'OR_2FG7_MIN_EXT', 'OR_2FG7_MIN_INT', 'OR_2FG7_POS_EXT', 'OR_2FG7_POS_INT', 'OR_2FG7_STATE', 'OR_3FG_BUSY', 'OR_3FG_CALIB', 'OR_3FG_FORCE', 'OR_3FG_FORCE_GRIP', 'OR_3FG_GRIP', 'OR_3FG_MAX_D', 'OR_3FG_MIN_D', 'OR_3FG_RAW_D', 'OR_3FG_REAL_D', 'OR_EYE_COUNT', 'OR_EYE_ERROR', 'OR_EYE_INSPECT_MATCH', 'OR_EYE_INSPECT_RESULT', 'OR_EYE_POS', 'OR_EYE_RX', 'OR_EYE_RY', 'OR_EYE_RZ', 'OR_EYE_X', 'OR_EYE_Y', 'OR_EYE_Z', 'OR_MG10_ERROR', 'OR_MG10_STATUS', 'OR_MG10_STRENGTH', 'OR_RG_BUSY', 'OR_RG_ERROR', 'OR_RG_GRIP', 'OR_RG_S1_PUSHED', 'OR_RG_S1_TRIGGERED', 'OR_RG_S2_PUSHED', 'OR_RG_S2_TRIGGERED', 'OR_RG_WIDTH', 'OR_SD_BUTTON', 'OR_SD_ERROR', 'OR_SD_MOTOR_RUNNING', 'OR_SD_MOTOR_STOPPED', 'OR_SD_RAMP_DW', 'OR_SD_RAMP_UP', 'OR_SD_RPM', 'OR_SD_RPM_DEV', 'OR_SD_RPM_TAR', 'OR_SD_STATUS', 'OR_SD_VIBRATION', 'OR_SD_WARNING', 'OR_SG_MAX_WIDTH', 'OR_SG_MIN_WIDTH', 'OR_SG_STATUS', 'OR_SG_WIDTH', 'OR_VGP20_A', 'OR_VGP20_A_GRIP', 'OR_VGP20_A_RELEASE', 'OR_VGP20_B', 'OR_VGP20_BUSY', 'OR_VGP20_B_GRIP', 'OR_VGP20_B_RELEASE', 'OR_VGP20_C', 'OR_VGP20_C_GRIP', 'OR_VGP20_C_RELEASE', 'OR_VGP20_D', 'OR_VGP20_D_GRIP', 'OR_VGP20_D_RELEASE', 'OR_VGP20_ERROR', 'OR_VG_A', 'OR_VG_B', 'OperationMode', 'PICKIT_BUILD_BKG_CLOUD_FAILED', 'PICKIT_BUILD_BKG_CLOUD_OK', 'PICKIT_CONFIG_FAILED', 'PICKIT_CONFIG_OK', 'PICKIT_EMPTY_ROI', 'PICKIT_FIND_CALIB_PLATE_FAILED', 'PICKIT_FIND_CALIB_PLATE_OK', 'PICKIT_GET_PICK_POINT_DATA_FAILED', 'PICKIT_GET_PICK_POINT_DATA_OK', 'PICKIT_IDLE_MODE', 'PICKIT_IMAGE_CAPTURED', 'PICKIT_M0', 'PICKIT_M1', 'PICKIT_NO_IMAGE_CAPTURED', 'PICKIT_NO_OBJECTS', 'PICKIT_OBJECT_FOUND', 'PICKIT_P0', 'PICKIT_P0F', 'PICKIT_P1', 'PICKIT_P1F', 'PICKIT_P2', 'PICKIT_P2F', 'PICKIT_P3', 'PICKIT_P3F', 'PICKIT_P4', 'PICKIT_P4F', 'PICKIT_P5', 'PICKIT_P5F', 'PICKIT_POS', 'PICKIT_ROBOTTYPE', 'PICKIT_ROBOT_MODE', 'PICKIT_RX', 'PICKIT_RY', 'PICKIT_RZ', 'PICKIT_SAVE_SNAPSHOT_FAILED', 'PICKIT_SAVE_SNAPSHOT_OK', 'PICKIT_STATUS', 'PICKIT_TYPE_BLOB', 'PICKIT_TYPE_CIRCLE', 'PICKIT_TYPE_CYLINDER', 'PICKIT_TYPE_ELLIPSE', 'PICKIT_TYPE_POINTCLOUD', 'PICKIT_TYPE_RECTANGLE', 'PICKIT_TYPE_SPHERE', 'PICKIT_TYPE_SQUARE', 'PICKIT_UNKNOWN_COMMAND', 'PICKIT_VERSION', 'PICKIT_X', 'PICKIT_Y', 'PICKIT_Z', 'RC_PICKIT_CAPTURE_IMAGE', 'RC_PICKIT_CHECK_MODE', 'RC_PICKIT_CONFIGURE', 'RC_PICKIT_FIND_CALIB_PLATE', 'RC_PICKIT_GET_PICK_POINT_DATA', 'RC_PICKIT_LOOK_FOR_OBJECTS', 'RC_PICKIT_LOOK_FOR_OBJECTS_WITH_RETRIES', 'RC_PICKIT_NEXT_OBJECT', 'RC_PICKIT_NO_COMMAND', 'RC_PICKIT_PROCESS_IMAGE', 'RC_PICKIT_SAVE_SCENE', 'RC_PICKIT_SET_CYLINDER_DIM', 'RC_SAVE_ACTIVE_PRODUCT', 'RC_SAVE_ACTIVE_SETUP', 'RC_SAVE_BUILD_BACKGROUND', 'ReferenceFrame', 'Response', 'ResponseCollector', 'ReturnType', 'RobotState', 'SD_ARM_POWER', 'SD_BEGIN_J0', 'SD_BEGIN_J1', 'SD_BEGIN_J2', 'SD_BEGIN_J3', 'SD_BEGIN_J4', 'SD_BEGIN_J5', 'SD_BIT_0_11', 'SD_BIT_0_15', 'SD_BIT_0_3', 'SD_BIT_0_7', 'SD_BIT_12_15', 'SD_BIT_4_7', 'SD_BIT_8_11', 'SD_COLLISION_DETECT_STATE', 'SD_CONV_POS_TICK', 'SD_CONV_VEL_TICK', 'SD_CURRENT_DELTA', 'SD_DEFAULT_SPEED', 'SD_DIGITAL_IN_CONFIG_0', 'SD_DIGITAL_IN_CONFIG_1', 'SD_DWELD_A', 'SD_DWELD_ARC', 'SD_DWELD_F', 'SD_DWELD_SET_A', 'SD_DWELD_TOUCH', 'SD_DWELD_V', 'SD_EMG_BUTTON_STATE', 'SD_FINISH_AT_EVENT', 'SD_FORCE_TRAVEL_DIS', 'SD_HAND_TOKTOK', 'SD_ID_NUMBER', 'SD_INBOX_CHECK_MODE_0', 'SD_INBOX_CHECK_MODE_1', 'SD_INBOX_TRAP_FLAG_0', 'SD_INBOX_TRAP_FLAG_1', 'SD_INIT_ERR', 'SD_INIT_STATE_INFO', 'SD_IS_BEGIN', 'SD_IS_FREE_DRIVE_MODE', 'SD_IS_HOME', 'SD_IS_INTENDED_STOP', 'SD_IS_IN_MAIN', 'SD_IS_RUN_IN_MAKE', 'SD_IS_RUN_IN_PLAY', 'SD_IS_TPU_CONNECT', 'SD_J0_ANG', 'SD_J0_CUR', 'SD_J0_REF', 'SD_J0_VEL', 'SD_J1_ANG', 'SD_J1_CUR', 'SD_J1_REF', 'SD_J1_VEL', 'SD_J2_ANG', 'SD_J2_CUR', 'SD_J2_REF', 'SD_J2_VEL', 'SD_J3_ANG', 'SD_J3_CUR', 'SD_J3_REF', 'SD_J3_VEL', 'SD_J4_ANG', 'SD_J4_CUR', 'SD_J4_REF', 'SD_J4_VEL', 'SD_J5_ANG', 'SD_J5_CUR', 'SD_J5_REF', 'SD_J5_VEL', 'SD_MOTION_TIME', 'SD_MOVE_INDEX', 'SD_MOVE_INDEX_F', 'SD_MOVE_PROPERTY', 'SD_NO_ARC_STATE', 'SD_OP_STAT_COLLISION_OCCUR', 'SD_OP_STAT_EMS_FLAG', 'SD_OP_STAT_ESTOP_OCCUR', 'SD_OP_STAT_SELF_COLLISION', 'SD_OP_STAT_SOS_FLAG', 'SD_PG_MODE', 'SD_POWER_STATE', 'SD_ROBOT_STATE', 'SD_SOCK_IS_OPEN_0', 'SD_SOCK_IS_OPEN_1', 'SD_SOCK_IS_OPEN_2', 'SD_SOCK_IS_OPEN_3', 'SD_SOCK_IS_OPEN_4', 'SD_SOCK_LAST_READ_0', 'SD_SOCK_LAST_READ_1', 'SD_SOCK_LAST_READ_2', 'SD_SOCK_LAST_READ_3', 'SD_SOCK_LAST_READ_4', 'SD_TCP_RX', 'SD_TCP_RY', 'SD_TCP_RZ', 'SD_TCP_VEL_REF', 'SD_TCP_X', 'SD_TCP_Y', 'SD_TCP_Z', 'SD_TEMPERATURE_MC0', 'SD_TEMPERATURE_MC1', 'SD_TEMPERATURE_MC2', 'SD_TEMPERATURE_MC3', 'SD_TEMPERATURE_MC4', 'SD_TEMPERATURE_MC5', 'SD_TFB_ANALOG_IN_0', 'SD_TFB_ANALOG_IN_1', 'SD_TFB_DIGITAL_IN_0', 'SD_TFB_DIGITAL_IN_1', 'SD_TFB_DIGITAL_OUT_0', 'SD_TFB_DIGITAL_OUT_1', 'SD_TFB_VOLTAGE_OUT', 'SD_TF_LRF_DISTANCE', 'SD_TF_LRF_QUALITY', 'SD_TIME', 'SD_TIMER_0', 'SD_TIMER_1', 'SD_TIMER_2', 'SD_TIMER_3', 'SD_TIMER_4', 'SD_TIMER_5', 'SD_TIMER_6', 'SD_TIMER_7', 'SD_TIMER_8', 'SD_TIMER_9', 'SETECH_ALM', 'SETECH_BUSY', 'SETECH_COMP', 'SETECH_NG_ANGH', 'SETECH_NG_ANGL', 'SETECH_NG_CH1', 'SETECH_NG_CH16', 'SETECH_NG_CH2', 'SETECH_NG_CH4', 'SETECH_NG_CH8', 'SETECH_NG_MONI', 'SETECH_NG_TIME', 'SETECH_NG_TRQH', 'SETECH_NG_TRQL', 'SETECH_OK', 'SETECH_RDY', 'SystemState', 'SystemVariable', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_rbpodo', 'annotations', 'asyncio', 'to_string']
